"""create organizers table

Revision ID: 625cad5808a1
Revises: da2ee106a3fe
Create Date: 2024-05-14 21:04:13.584966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '625cad5808a1'
down_revision = 'da2ee106a3fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organizers')
    # ### end Alembic commands ###
