"""create events table

Revision ID: 6374fa13b929
Revises: 7f0902a752a5
Create Date: 2024-05-15 00:22:44.651541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6374fa13b929'
down_revision = '7f0902a752a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=254), nullable=False),
    sa.Column('address', sa.String(length=254), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time_in', sa.Time(), nullable=False),
    sa.Column('time_out', sa.Time(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('radius', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
