"""add profile to students table

Revision ID: a8eba415686f
Revises: 5463165e989d
Create Date: 2024-05-15 10:37:47.970822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8eba415686f'
down_revision = '5463165e989d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile', sa.String(length=254), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('profile')

    # ### end Alembic commands ###
