"""create departments table

Revision ID: da2ee106a3fe
Revises: 559d2156bfb0
Create Date: 2024-05-14 20:36:41.784936

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "da2ee106a3fe"
down_revision = "559d2156bfb0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "departments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("departments")
    # ### end Alembic commands ###
